{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}-config
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
