{{- if .Values.authService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.authService.name }}-config
data:
  {{- range $key, $value := .Values.authService.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
