{{- if .Values.jwtSecret.key }}
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # JWT_SECRET_KEY encoded in base64 (used by backend and auth-service) (used by backend and auth-service)
  JWT_SECRET_KEY: {{ .Values.jwtSecret.key | b64enc | quote }}
{{- end }}
